service:
  name: "Example"

kafka:
  consumer:
    groupId: "example-app"
    clientId: "example-client"
    bootstrapServers:
      - "172.29.188.32:9092"
    autoCommitInterval: 10

redis:
  host: "localhost:3000"
  user: "admin"
  password: "abc"